/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_loginid_cryptodid_protocols_TfheVerifier */

#ifndef _Included_com_loginid_cryptodid_protocols_TfheVerifier
#define _Included_com_loginid_cryptodid_protocols_TfheVerifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_loginid_cryptodid_protocols_TfheVerifier
 * Method:    verifyAge
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loginid_cryptodid_protocols_TfheVerifier_verifyAge
  (JNIEnv *, jobject);

/*
 * Class:     com_loginid_cryptodid_protocols_TfheVerifier
 * Method:    verifyBalance
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loginid_cryptodid_protocols_TfheVerifier_verifyBalance
  (JNIEnv *, jobject);

/*
 * Class:     com_loginid_cryptodid_protocols_TfheVerifier
 * Method:    CreditScore
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loginid_cryptodid_protocols_TfheVerifier_CreditScore
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
